spring:
  vitess:
    jdbcUrl: jdbc:mysql://localhost:3306/riskquotient?reWriteBatchedInserts=true
    password: root
    username: root
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    hikari:
      connection-timeout: 20000
      minimum-idle: 10 
      maximum-pool-size: 90
      idle-timeout: 10000
      max-lifetime: 1000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      generate_statistics: false
      show_sql: true
      format_sql: true
      
  batch:
     job.enabled: false
     initialize-schema: always
  main.allow-bean-definition-overriding: true
      
     
      
logging:
  level:
    org.springframework.web: debug
    com.csw.shiftleft: debug
    org.hibernate: error
  file:
    name: logs/data-shiftleft-api-dev.log
    clean-history-on-start: true
    max-history: 1
    max-size: 10MB
  pattern: 
     file: "%d %-5level [%thread] [${spring.application.name},%X{traceId},%X{spanId},%X{MSG_ID}] %logger{0}: %msg%n"
     console: "%d %-5level [%thread] [${spring.application.name},%X{traceId},%X{spanId},%X{MSG_ID}] %logger{0}: %msg%n"

aws:
   s3-bucket-name: us-east-1.dev.risk-quotient.csw.com
   aws_access_key_id: ASIAWOFRCKO2AHPCJMNY
   aws_secret_access_key: uolDETeVkVZIe26ilvsjhjwc4/VS327nGh098nUr
   seller.session: IQoJb3JpZ2luX2VjEFYaCXVzLWVhc3QtMSJGMEQCIAIRxSFIbhHD7XoqPfeF0oGR+pY4Ngq5qnvv8URNAvkhAiB8kWJElMZFLb2/xCQXDbftw6RR9s5FsnHIUMcMehJ7CyqvAwheEAEaDDQ0Mjc1Mjk3OTg5MiIMzppQfBn/yFM+apeGKowDhw/RhOYHu1tBjPYHIpsTiaBaael/Ocztloaz6vtIHvLztcges3dRKH/KMfwdJee3yqoSJony19cntHAbNJFObezbIMo55mCCwVlKW/2A2DhCbZ64r7knwQ1jqHdEoBRXnTTsmyV2Z/MvJd3UQ6PD7HuzvLeUK0waEGduWpgVffWYhvzCk9D6fEimjaSqFkIJ7+7o/kruTh5/MB3c9DnVUXp8aaLWwaqF3jxgbi+YmjnIVuVX6GlKXh2/o2VxlQVijZl+N8Si6IpMj3slIrKDcp2I/SGvHO8AxfhDsfoyGbsBpiK3Xm2icds9L6S5QlXg+yW8P5Bk6QUzBUMnUQ7V+i8srhxnBTSS5Dcmkroxp+JR1kXczAtgMFOOv3STYI1y1PrlVboaX0E8yVr3sXGroK1u/FxQX7ZLP/Gh9SOJsJHcJBk5tdVSMDo/q44m6mo7PHzWudzeGShSzUO1TMzJ3Hf6bfeupstwWhbfDvS8uDXlxbNfPvsv/iQmUADvGicm0l8JMWKTvQWiKsUFMMCJgIgGOqcBRDUWwMngOGvREhdUpgsW7rgH+jBsCoi/YvIObwH9ZPJjz7r4KlXUwgiMAUKD7xr2m4VKjVZ7E9p6Lc/36fXrhODJAsRQoLsWQ1BgkOAEBoSLcc5Fc724YAC0HSli3OhxIWILwY0DAN0T558hdhD1avg9aR3PNiDPhoGRKFqZgqKngUAIJL+3cLZJgZ9M96ywfe99A7dvTZhins4adpAbSVR/QjY9szA=
   seller.role-arn: arn:aws:iam::442752979892:role/shiftleft-ecrRole
      
data-ingestion:
     url: http://localhost:9095     
    
  
